services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    volumes:
      - praiseapp-mongodb-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    depends_on:
      - mongo
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
  praiseapp-mongodb-data: