import { useState, KeyboardEvent } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { Link, useNavigate } from 'react-router'
import toast from 'react-hot-toast'
import dayjs from 'dayjs'
import 'dayjs/locale/es'
import {
  Box,
  Button,
  Flex,
  Paper,
  Text,
  Title,
  Input,
  ActionIcon
} from '@praise-app/ui-kit'
import { DatePickerInput } from '@mantine/dates'
import { IconX, IconPlus, IconCalendar } from '@tabler/icons-react'
import { Navbar } from '../../components/Navbar'
import { useSaveSetlistMutation } from '../../hooks'
import { AddSongModal } from './AddSongModal'
import type { SaveSetlistSong, SaveSetlistRequest } from '../../api/setlists/post'

dayjs.locale('es')

interface SaveSetlistFormData {
  name: string
  date: Date | null
  tags: string[]
  songs: SaveSetlistSong[]
}

export function SaveSetlistPage () {
  const navigate = useNavigate()
  const saveSetlistMutation = useSaveSetlistMutation()

  const [isAddSongModalOpen, setIsAddSongModalOpen] = useState(false)
  const [currentTag, setCurrentTag] = useState('')

  const {
    register,
    handleSubmit,
    control,
    setValue,
    watch,
    formState: { errors, isSubmitting }
  } = useForm<SaveSetlistFormData>({
    defaultValues: {
      name: '',
      date: null,
      tags: [],
      songs: []
    }
  })

  const formDate = watch('date')
  const formName = watch('name')

  const generateNameFromDate = (dateVal: Date | null) => {
    if (!dateVal) return ''
    const generated = dayjs(dateVal).format('dddd DD/MM/YY')
    return generated.charAt(0).toUpperCase() + generated.slice(1)
  }

  // Handle auto-updating the name if it's empty or matches previous auto-generated name
  const handleDateChange = (newDate: Date | null) => {
    const oldAutoName = generateNameFromDate(formDate)
    setValue('date', newDate, { shouldValidate: true })

    // If the name is currently empty, or matches the old autogenerated name, update it automatically
    if (!formName.trim() || formName === oldAutoName) {
      setValue('name', generateNameFromDate(newDate), { shouldValidate: true })
    }
  }

  const addTag = () => {
    const trimmedTag = currentTag.trim()
    if (trimmedTag && !watch('tags').includes(trimmedTag)) {
      const currentTags = watch('tags')
      setValue('tags', [...currentTags, trimmedTag], { shouldValidate: true })
      setCurrentTag('')
    }
  }

  const removeTag = (tagToRemove: string) => {
    const currentTags = watch('tags')
    setValue(
      'tags',
      currentTags.filter((tag) => tag !== tagToRemove),
      { shouldValidate: true }
    )
  }

  const handleTagInputKeyPress = (e: KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault()
      addTag()
    }
  }

  const handleAddSong = (song: SaveSetlistSong) => {
    const currentSongs = watch('songs')
    setValue('songs', [...currentSongs, song], { shouldValidate: true })
    toast.success('Song added to setlist!')
  }

  const removeSong = (indexToRemove: number) => {
    const currentSongs = watch('songs')
    setValue(
      'songs',
      currentSongs.filter((_, idx) => idx !== indexToRemove),
      { shouldValidate: true }
    )
  }

  const onSubmit = async (data: SaveSetlistFormData) => {
    if (!data.date) {
      toast.error('Please select a date')
      return
    }

    try {
      const requestData: SaveSetlistRequest = {
        name: data.name || generateNameFromDate(data.date),
        date: data.date,
        tags: data.tags,
        songs: data.songs
      }

      await saveSetlistMutation.mutateAsync(requestData)
      toast.success('Setlist saved successfully!')
      navigate('/setlists')
    } catch (error) {
      console.error(error)
      toast.error(error instanceof Error ? error.message : 'Failed to save setlist')
    }
  }

  return (
    <Box>
      <Navbar />
      <Box p="md">
        <Flex align="center" justify="space-between" gap="md" mb="md">
          <Title order={1} m={0}>
            Create Setlist
          </Title>
          <Button component={Link} to="/setlists" variant="light">
            Back to Setlists
          </Button>
        </Flex>

        <Box maw={1000} mx="auto">
          <Paper p="md" radius="md" withBorder>
            <form onSubmit={handleSubmit(onSubmit)}>
              <Flex direction="column" gap="md">

                <Flex direction="column" gap="xs">
                  <Text fw={500}>Date *</Text>
                  <Controller
                    name="date"
                    control={control}
                    rules={{ required: 'Date is required' }}
                    render={({ field }) => (
                      <DatePickerInput
                        leftSection={<IconCalendar size={16} stroke={1.5} />}
                        placeholder="Pick a date"
                        value={field.value}
                        onChange={(val: any) => {
                          field.onChange(val)
                          handleDateChange(val)
                        }}
                        error={errors.date?.message as string}
                        clearable
                      />
                    )}
                  />
                </Flex>

                <Flex direction="column" gap="xs">
                  <Text fw={500}>Setlist Name *</Text>
                  <Input
                    placeholder="E.g. Domingo 26/03/24"
                    {...register('name', { required: 'Setlist name is required' })}
                    error={errors.name?.message}
                  />
                </Flex>

                <Flex direction="column" gap="xs">
                  <Text fw={500}>Tags</Text>
                  <Flex direction="column" gap="sm">
                    <Flex gap="sm">
                      <Input
                        placeholder="Enter a tag and press Enter or Add"
                        value={currentTag}
                        onChange={(e) => setCurrentTag(e.target.value)}
                        onKeyPress={handleTagInputKeyPress}
                        style={{ flex: 1 }}
                      />
                      <Button
                        type="button"
                        variant="light"
                        onClick={addTag}
                        disabled={!currentTag.trim() || watch('tags').includes(currentTag.trim())}
                      >
                        Add
                      </Button>
                    </Flex>
                    {watch('tags').length > 0 && (
                      <Flex gap="xs" wrap="wrap">
                        {watch('tags').map((tag, index) => (
                          <Flex
                            key={index}
                            gap={4}
                            align="center"
                            px={8}
                            py={4}
                            bg="var(--mantine-color-gray-0)"
                            bd="1px solid var(--mantine-color-gray-3)"
                            style={{ borderRadius: 'var(--mantine-radius-default)' }}
                          >
                            <Text size="sm">{tag}</Text>
                            <ActionIcon
                              size="sm"
                              variant="subtle"
                              color="gray"
                              onClick={() => removeTag(tag)}
                            >
                              <IconX size={12} />
                            </ActionIcon>
                          </Flex>
                        ))}
                      </Flex>
                    )}
                  </Flex>
                </Flex>

                <Flex direction="column" gap="xs">
                  <Flex align="center" justify="space-between" mb="xs">
                    <Text fw={500}>Songs</Text>
                    <Button
                      type="button"
                      size="sm"
                      variant="light"
                      leftSection={<IconPlus size={14} />}
                      onClick={() => setIsAddSongModalOpen(true)}
                    >
                      Add Song
                    </Button>
                  </Flex>

                  {watch('songs').length === 0
                    ? (
                    <Text c="dimmed" size="sm">No songs added yet.</Text>
                      )
                    : (
                    <Flex direction="column" gap="xs">
                      {watch('songs').map((song, index) => (
                        <Paper key={index} p="sm" withBorder radius="md">
                          <Flex align="center" justify="space-between">
                            <Box>
                              <Text fw={500}>{song.name}</Text>
                              <Text size="sm" c="dimmed">
                                Tempo: {song.tempo.tempo} BPM ({song.tempo.variant}) • Key: {song.key.key} ({song.key.variant})
                              </Text>
                            </Box>
                            <ActionIcon
                              color="red"
                              variant="light"
                              onClick={() => removeSong(index)}
                            >
                              <IconX size={16} />
                            </ActionIcon>
                          </Flex>
                        </Paper>
                      ))}
                    </Flex>
                      )}
                </Flex>

                <Flex gap="sm" mt="md">
                  <Button type="submit" loading={isSubmitting}>
                    Save Setlist
                  </Button>
                  <Button component={Link} to="/setlists" variant="light">
                    Cancel
                  </Button>
                </Flex>
              </Flex>
            </form>
          </Paper>
        </Box>
      </Box>

      {/* Add Song Modal */}
      <AddSongModal
        opened={isAddSongModalOpen}
        onClose={() => setIsAddSongModalOpen(false)}
        onAdd={handleAddSong}
      />
    </Box>
  )
}
